services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgresqldata:/var/lib/postgresql/data
  go:
    container_name: go
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  postgresqldata: